#!/bin/sh
# Extract CMake macros during configure 

pip2 install --upgrade pip
pip2 install zeroc-ice

echo "/opt/jderobot/lib/jderobot/" > /etc/ld.so.conf.d/jderobot.conf
echo "source /opt/jderobot/setup.bash" >> ~/.bashrc
echo "source /opt/ros/kinetic/setup.bash" >> ~/.bashrc
source ~/.bashrc 
ldconfig
