// **********************************************************************
//
// Copyright (c) 2003-2014 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `remoteCloud.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(global, r)
{
    var require = typeof(r) === "function" ? r : function(){};
    require("Ice/Object");
    require("Ice/ObjectPrx");
    require("Ice/Operation");
    require("Ice/Long");
    require("Ice/HashMap");
    require("Ice/HashUtil");
    require("Ice/ArrayUtil");
    require("Ice/StreamHelpers");
    
    var Ice = global.Ice || {};
    require("pointcloud");
    
    var jderobot = global.jderobot || {};

    jderobot.remoteCloud = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            jderobot.pointCloud
        ], 2,
        [
            "::Ice::Object",
            "::jderobot::pointCloud",
            "::jderobot::remoteCloud"
        ],
        -1, undefined, undefined, false);

    jderobot.remoteCloudPrx = Slice.defineProxy(Ice.ObjectPrx, jderobot.remoteCloud.ice_staticId, [
        jderobot.pointCloudPrx]);

    Slice.defineOperations(jderobot.remoteCloud, jderobot.remoteCloudPrx,
    {
        "initConfiguration": [, , , , , [3], , , , , ],
        "read": [, , , , , [7], [[3]], , , , ],
        "write": [, , , , , [3], [[7], [3]], , , , ],
        "setConfiguration": [, , , , , [3], [[3]], , , , ]
    });
    global.jderobot = jderobot;
}
(typeof (global) === "undefined" ? window : global, typeof (require) === "undefined" ? undefined : require));
