#!/bin/sh

set -e

test -d src/stable && test -d src/testing

# remove cmake_(un)?install.cmake files
find -type f -name cmake_install.cmake -o -name cmake_uninstall.cmake -exec rm {} +

# remove Makefile files
find src -type f -name Makefile -exec rm {} +
test -d CMakeFiles \
    && find CMakeFiles -type f -name Makefile -exec rm {} + \
    || true
rm -f Makefile

# remove CMakeFiles dirs
find -type d -name CMakeFiles -exec rm -r {} +

# remove CMakeCache.txt files
find -type f -name CMakeCache.txt -exec rm {} +

# remove generated interface source files
langdirs=`find src/stable/interfaces -mindepth 1 -maxdepth 1 -type d ! -name slice`
for langdir in $langdirs; do
    find "$langdir" -type f ! -name '*.tmp' -a ! -name '.keepme' -exec rm {} +
done

rm -f src/stable/libs/*/*.so
rm -f src/stable/libs/*/*.a
