#!/bin/sh

mivar=`du -a | grep cmake_install.cmake | awk '{print $2}'`

mv ./doc/paper-autonomous_robots/Makefile /tmp

for file in $mivar; do
	rm -f $file
done

mivar=`du -a | grep Makefile$ | awk '{print $2}'`


for file in $mivar; do
	rm -f $file
done

mivar=`du -a | grep CMakeFiles | awk '{print $2}'`


for file in $mivar; do
	rm -fr $file
done

mivar=`du -a | grep CMakeCache.txt | awk '{print $2}'`


for file in $mivar; do
	rm -fr $file
done

rm -f src/stable/interfaces/cpp/jderobot/*

mivar=`du -a | grep "cmake_uninstall.cmake$" | awk '{print $2}'`

for file in $mivar; do
	rm -fr $file
done

rm -f src/stable/libs/*/*.so
rm -f src/stable/libs/*/*.a




mv /tmp/Makefile ./doc/paper-autonomous_robots
