// **********************************************************************
//
// Copyright (c) 2003-2014 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `body.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(global, r)
{
    var require = typeof(r) === "function" ? r : function(){};
    require("Ice/Struct");
    require("Ice/EnumBase");
    require("Ice/Long");
    require("Ice/HashMap");
    require("Ice/HashUtil");
    require("Ice/ArrayUtil");
    require("Ice/StreamHelpers");
    
    var Ice = global.Ice || {};
    require("common");
    
    var jderobot = global.jderobot || {};

    jderobot.BodySide = Slice.defineEnum({
        'Left':0, 'Right':1});

    jderobot.CameraBody = Slice.defineEnum({
        'Top':0, 'Bottom':1});

    jderobot.MotorsName = Slice.defineEnum({
        'HipYawPitch':0, 'HipPitch':1, 'HipRoll':2, 'KneePitch':3, 'AnklePitch':4,
        'AnkleRoll':5, 'ShoulderPitch':6, 'ShoulderRoll':7, 'ElbowYaw':8, 'ElbowRoll':9});

    /**
     * simply body motor
     **/
    jderobot.BodyMotor = Slice.defineStruct(
        function(pitch, yaw, roll)
        {
            this.pitch = pitch !== undefined ? pitch : 0.0;
            this.yaw = yaw !== undefined ? yaw : 0.0;
            this.roll = roll !== undefined ? roll : 0.0;
        },
        false,
        function(__os)
        {
            __os.writeFloat(this.pitch);
            __os.writeFloat(this.yaw);
            __os.writeFloat(this.roll);
        },
        function(__is)
        {
            this.pitch = __is.readFloat();
            this.yaw = __is.readFloat();
            this.roll = __is.readFloat();
        },
        12, 
        true);
    global.jderobot = jderobot;
}
(typeof (global) === "undefined" ? window : global, typeof (require) === "undefined" ? undefined : require));
