// **********************************************************************
//
// Copyright (c) 2003-2014 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `bodymotors.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(global, r)
{
    var require = typeof(r) === "function" ? r : function(){};
    require("Ice/Object");
    require("Ice/ObjectPrx");
    require("Ice/Operation");
    require("Ice/Long");
    require("Ice/HashMap");
    require("Ice/HashUtil");
    require("Ice/ArrayUtil");
    require("Ice/StreamHelpers");
    
    var Ice = global.Ice || {};
    require("common");
    
    var jderobot = global.jderobot || {};
    require("body");

    /**
     * BodyMotorsParam 
     **/
    jderobot.BodyMotorsParam = Slice.defineObject(
        function(minAngle, maxAngle, maxSpeed)
        {
            Ice.Object.call(this);
            this.minAngle = minAngle !== undefined ? minAngle : 0.0;
            this.maxAngle = maxAngle !== undefined ? maxAngle : 0.0;
            this.maxSpeed = maxSpeed !== undefined ? maxSpeed : 0.0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::jderobot::BodyMotorsParam"
        ],
        -1,
        function(__os)
        {
            __os.writeFloat(this.minAngle);
            __os.writeFloat(this.maxAngle);
            __os.writeFloat(this.maxSpeed);
        },
        function(__is)
        {
            this.minAngle = __is.readFloat();
            this.maxAngle = __is.readFloat();
            this.maxSpeed = __is.readFloat();
        },
        false);

    jderobot.BodyMotorsParamPrx = Slice.defineProxy(Ice.ObjectPrx, jderobot.BodyMotorsParam.ice_staticId, undefined);

    Slice.defineOperations(jderobot.BodyMotorsParam, jderobot.BodyMotorsParamPrx);

    /**
     * Interface to the Humanoid Body Motors.
     **/
    jderobot.BodyMotors = Slice.defineObject(
        undefined,
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::jderobot::BodyMotors"
        ],
        -1, undefined, undefined, false);

    jderobot.BodyMotorsPrx = Slice.defineProxy(Ice.ObjectPrx, jderobot.BodyMotors.ice_staticId, undefined);

    Slice.defineOperations(jderobot.BodyMotors, jderobot.BodyMotorsPrx,
    {
        "getBodyMotorsParam": [, 2, 2, , , ["jderobot.BodyMotorsParam", true], [[jderobot.MotorsName.__helper], [jderobot.BodySide.__helper]], , , , true],
        "setBodyMotorsData": [, , , , , [3], [[jderobot.MotorsName.__helper], [jderobot.BodySide.__helper], [5], [5]], , , , ]
    });
    global.jderobot = jderobot;
}
(typeof (global) === "undefined" ? window : global, typeof (require) === "undefined" ? undefined : require));
