# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_gui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 550)
        MainWindow.setMinimumSize(QtCore.QSize(790, 550))
        MainWindow.setMaximumSize(QtCore.QSize(790, 550))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.takeoffButton = QtWidgets.QPushButton(self.centralwidget)
        self.takeoffButton.setGeometry(QtCore.QRect(80, 370, 161, 41))
        self.takeoffButton.setObjectName("takeoffButton")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(80, 420, 161, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon)
        self.stopButton.setObjectName("stopButton")
        self.windowsLabel = QtWidgets.QLabel(self.centralwidget)
        self.windowsLabel.setGeometry(QtCore.QRect(280, 390, 71, 21))
        self.windowsLabel.setObjectName("windowsLabel")
        self.cameraCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.cameraCheck.setGeometry(QtCore.QRect(280, 420, 94, 26))
        self.cameraCheck.setObjectName("cameraCheck")
        self.sensorsCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.sensorsCheck.setGeometry(QtCore.QRect(280, 450, 94, 26))
        self.sensorsCheck.setObjectName("sensorsCheck")
        self.altdLabel = QtWidgets.QLabel(self.centralwidget)
        self.altdLabel.setGeometry(QtCore.QRect(440, 340, 61, 21))
        self.altdLabel.setObjectName("altdLabel")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 361, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.tlLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.tlLayout.setObjectName("tlLayout")
        self.rotationLabel = QtWidgets.QLabel(self.centralwidget)
        self.rotationLabel.setGeometry(QtCore.QRect(640, 340, 65, 21))
        self.rotationLabel.setObjectName("rotationLabel")
        self.XLabel = QtWidgets.QLabel(self.centralwidget)
        self.XLabel.setGeometry(QtCore.QRect(20, 340, 21, 21))
        self.XLabel.setObjectName("XLabel")
        self.YLabel = QtWidgets.QLabel(self.centralwidget)
        self.YLabel.setGeometry(QtCore.QRect(130, 340, 21, 21))
        self.YLabel.setObjectName("YLabel")
        self.XValue = QtWidgets.QLabel(self.centralwidget)
        self.XValue.setGeometry(QtCore.QRect(40, 340, 41, 21))
        self.XValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.XValue.setObjectName("XValue")
        self.YValue = QtWidgets.QLabel(self.centralwidget)
        self.YValue.setGeometry(QtCore.QRect(150, 340, 41, 21))
        self.YValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.YValue.setObjectName("YValue")
        self.altdValue = QtWidgets.QLabel(self.centralwidget)
        self.altdValue.setGeometry(QtCore.QRect(520, 340, 41, 21))
        self.altdValue.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.altdValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.altdValue.setObjectName("altdValue")
        self.rotValue = QtWidgets.QLabel(self.centralwidget)
        self.rotValue.setGeometry(QtCore.QRect(710, 340, 41, 21))
        self.rotValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rotValue.setObjectName("rotValue")
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(80, 470, 161, 41))
        self.resetButton.setObjectName("resetButton")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(410, 30, 361, 301))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.tlLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.tlLayout_1.setObjectName("tlLayout_1")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(640, 370, 131, 151))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/images/jderobot.png"))
        self.logo.setObjectName("logo")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UAV_Viewer"))
        self.takeoffButton.setText(_translate("MainWindow", "Take off"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.windowsLabel.setText(_translate("MainWindow", "Windows:"))
        self.cameraCheck.setText(_translate("MainWindow", "Camera"))
        self.sensorsCheck.setText(_translate("MainWindow", "Sensors"))
        self.altdLabel.setText(_translate("MainWindow", "Altitude:"))
        self.rotationLabel.setText(_translate("MainWindow", "Rotation:"))
        self.XLabel.setText(_translate("MainWindow", "X:"))
        self.YLabel.setText(_translate("MainWindow", "Y:"))
        self.XValue.setText(_translate("MainWindow", "0"))
        self.YValue.setText(_translate("MainWindow", "0"))
        self.altdValue.setText(_translate("MainWindow", "0"))
        self.rotValue.setText(_translate("MainWindow", "0"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))

import resources_rc
