#!/bin/bash

# Enter your sudo pass for reset usb device automatically
PASS_SUDO=

mkdir -p ../log/
echo "Restarting openniServer ... " `date` >> ../log/system.log

cd ..
./openniServer --Ice.Config=openniServer.cfg

