Document: jde
Title: Debian jde Manual
Author: <insert document author here>
Abstract: This manual describes what jde is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jde/jde.sgml.gz

Format: postscript
Files: /usr/share/doc/jde/jde.ps.gz

Format: text
Files: /usr/share/doc/jde/jde.text.gz

Format: HTML
Index: /usr/share/doc/jde/html/index.html
Files: /usr/share/doc/jde/html/*.html


