Document: jderobot
Title: Debian jderobot Manual
Author: <insert document author here>
Abstract: This manual describes what jderobot is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jderobot/jderobot.sgml.gz

Format: postscript
Files: /usr/share/doc/jderobot/jderobot.ps.gz

Format: text
Files: /usr/share/doc/jderobot/jderobot.text.gz

Format: HTML
Index: /usr/share/doc/jderobot/html/index.html
Files: /usr/share/doc/jderobot/html/*.html
