// Generated by gencpp from file roscompat/Pose3d.msg
// DO NOT EDIT!


#ifndef ROSCOMPAT_MESSAGE_POSE3D_H
#define ROSCOMPAT_MESSAGE_POSE3D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roscompat
{
template <class ContainerAllocator>
struct Pose3d_
{
  typedef Pose3d_<ContainerAllocator> Type;

  Pose3d_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , h(0.0)
    , q0(0.0)
    , q1(0.0)
    , q2(0.0)
    , q3(0.0)  {
    }
  Pose3d_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , h(0.0)
    , q0(0.0)
    , q1(0.0)
    , q2(0.0)
    , q3(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _h_type;
  _h_type h;

   typedef double _q0_type;
  _q0_type q0;

   typedef double _q1_type;
  _q1_type q1;

   typedef double _q2_type;
  _q2_type q2;

   typedef double _q3_type;
  _q3_type q3;




  typedef boost::shared_ptr< ::roscompat::Pose3d_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roscompat::Pose3d_<ContainerAllocator> const> ConstPtr;

}; // struct Pose3d_

typedef ::roscompat::Pose3d_<std::allocator<void> > Pose3d;

typedef boost::shared_ptr< ::roscompat::Pose3d > Pose3dPtr;
typedef boost::shared_ptr< ::roscompat::Pose3d const> Pose3dConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roscompat::Pose3d_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roscompat::Pose3d_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roscompat

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'HasHeader': False, 'IsFixedSize': True}
// {'std_msgs': ['/home/fqez/ROS_cv/install_isolated/share/std_msgs/cmake/../msg'], 'roscompat': ['/home/fqez/github/testing/5.4.2/src/libs/roscompat/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::roscompat::Pose3d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscompat::Pose3d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscompat::Pose3d_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscompat::Pose3d_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roscompat::Pose3d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roscompat::Pose3d_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roscompat::Pose3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9fcf1c8fc344bc3dd0b6740d4de1f9d2";
  }

  static const char* value(const ::roscompat::Pose3d_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9fcf1c8fc344bc3dULL;
  static const uint64_t static_value2 = 0xd0b6740d4de1f9d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::roscompat::Pose3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roscompat/Pose3d";
  }

  static const char* value(const ::roscompat::Pose3d_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roscompat::Pose3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
float64 h\n\
float64 q0\n\
float64 q1\n\
float64 q2\n\
float64 q3\n\
";
  }

  static const char* value(const ::roscompat::Pose3d_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roscompat::Pose3d_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.h);
      stream.next(m.q0);
      stream.next(m.q1);
      stream.next(m.q2);
      stream.next(m.q3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Pose3d_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roscompat::Pose3d_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roscompat::Pose3d_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "h: ";
    Printer<double>::stream(s, indent + "  ", v.h);
    s << indent << "q0: ";
    Printer<double>::stream(s, indent + "  ", v.q0);
    s << indent << "q1: ";
    Printer<double>::stream(s, indent + "  ", v.q1);
    s << indent << "q2: ";
    Printer<double>::stream(s, indent + "  ", v.q2);
    s << indent << "q3: ";
    Printer<double>::stream(s, indent + "  ", v.q3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSCOMPAT_MESSAGE_POSE3D_H
