// **********************************************************************
//
// Copyright (c) 2003-2014 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `datetime.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(global, r)
{
    var require = typeof(r) === "function" ? r : function(){};
    require("Ice/Struct");
    require("Ice/Long");
    require("Ice/HashMap");
    require("Ice/HashUtil");
    require("Ice/ArrayUtil");
    require("Ice/StreamHelpers");
    
    var Ice = global.Ice || {};
    var jderobot = global.jderobot ||  {};

    jderobot.Time = Slice.defineStruct(
        function(seconds, useconds)
        {
            this.seconds = seconds !== undefined ? seconds : 0;
            this.useconds = useconds !== undefined ? useconds : 0;
        },
        true,
        function(__os)
        {
            __os.writeLong(this.seconds);
            __os.writeLong(this.useconds);
        },
        function(__is)
        {
            this.seconds = __is.readLong();
            this.useconds = __is.readLong();
        },
        16, 
        true);
    global.jderobot = jderobot;
}
(typeof (global) === "undefined" ? window : global, typeof (require) === "undefined" ? undefined : require));
