// **********************************************************************
//
// Copyright (c) 2003-2014 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `kinectleds.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(global, r)
{
    var require = typeof(r) === "function" ? r : function(){};
    require("Ice/Object");
    require("Ice/ObjectPrx");
    require("Ice/Operation");
    require("Ice/EnumBase");
    require("Ice/Long");
    require("Ice/HashMap");
    require("Ice/HashUtil");
    require("Ice/ArrayUtil");
    require("Ice/StreamHelpers");
    
    var Ice = global.Ice || {};
    var jderobot = global.jderobot ||  {};

    jderobot.KinectLedsAvailable = Slice.defineEnum({
        'OFF':0, 'GREEN':1, 'RED':2, 'YELLOW':3, 'BLINKGREEN':4,
        'BLINKYELLOW':5, 'BLINKRED':6});

    /**
     * Interface to the Kinect LEDS.
     **/
    jderobot.KinectLeds = Slice.defineObject(
        undefined,
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::jderobot::KinectLeds"
        ],
        -1, undefined, undefined, false);

    jderobot.KinectLedsPrx = Slice.defineProxy(Ice.ObjectPrx, jderobot.KinectLeds.ice_staticId, undefined);

    Slice.defineOperations(jderobot.KinectLeds, jderobot.KinectLedsPrx,
    {
        "setLedActive": [, , , , , , [[jderobot.KinectLedsAvailable.__helper]], , , , ]
    });
    global.jderobot = jderobot;
}
(typeof (global) === "undefined" ? window : global, typeof (require) === "undefined" ? undefined : require));
