// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MotorSpeed.proto

#ifndef PROTOBUF_MotorSpeed_2eproto__INCLUDED
#define PROTOBUF_MotorSpeed_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace mav_msgs {
namespace msgs {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MotorSpeed_2eproto();
void protobuf_AssignDesc_MotorSpeed_2eproto();
void protobuf_ShutdownFile_MotorSpeed_2eproto();

class MotorSpeed;

// ===================================================================

class MotorSpeed : public ::google::protobuf::Message {
 public:
  MotorSpeed();
  virtual ~MotorSpeed();

  MotorSpeed(const MotorSpeed& from);

  inline MotorSpeed& operator=(const MotorSpeed& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MotorSpeed& default_instance();

  void Swap(MotorSpeed* other);

  // implements Message ----------------------------------------------

  MotorSpeed* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MotorSpeed& from);
  void MergeFrom(const MotorSpeed& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float motor_speed = 1 [packed = true];
  inline int motor_speed_size() const;
  inline void clear_motor_speed();
  static const int kMotorSpeedFieldNumber = 1;
  inline float motor_speed(int index) const;
  inline void set_motor_speed(int index, float value);
  inline void add_motor_speed(float value);
  inline const ::google::protobuf::RepeatedField< float >&
      motor_speed() const;
  inline ::google::protobuf::RepeatedField< float >*
      mutable_motor_speed();

  // @@protoc_insertion_point(class_scope:mav_msgs.msgs.MotorSpeed)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< float > motor_speed_;
  mutable int _motor_speed_cached_byte_size_;
  friend void  protobuf_AddDesc_MotorSpeed_2eproto();
  friend void protobuf_AssignDesc_MotorSpeed_2eproto();
  friend void protobuf_ShutdownFile_MotorSpeed_2eproto();

  void InitAsDefaultInstance();
  static MotorSpeed* default_instance_;
};
// ===================================================================


// ===================================================================

// MotorSpeed

// repeated float motor_speed = 1 [packed = true];
inline int MotorSpeed::motor_speed_size() const {
  return motor_speed_.size();
}
inline void MotorSpeed::clear_motor_speed() {
  motor_speed_.Clear();
}
inline float MotorSpeed::motor_speed(int index) const {
  // @@protoc_insertion_point(field_get:mav_msgs.msgs.MotorSpeed.motor_speed)
  return motor_speed_.Get(index);
}
inline void MotorSpeed::set_motor_speed(int index, float value) {
  motor_speed_.Set(index, value);
  // @@protoc_insertion_point(field_set:mav_msgs.msgs.MotorSpeed.motor_speed)
}
inline void MotorSpeed::add_motor_speed(float value) {
  motor_speed_.Add(value);
  // @@protoc_insertion_point(field_add:mav_msgs.msgs.MotorSpeed.motor_speed)
}
inline const ::google::protobuf::RepeatedField< float >&
MotorSpeed::motor_speed() const {
  // @@protoc_insertion_point(field_list:mav_msgs.msgs.MotorSpeed.motor_speed)
  return motor_speed_;
}
inline ::google::protobuf::RepeatedField< float >*
MotorSpeed::mutable_motor_speed() {
  // @@protoc_insertion_point(field_mutable_list:mav_msgs.msgs.MotorSpeed.motor_speed)
  return &motor_speed_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace mav_msgs

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MotorSpeed_2eproto__INCLUDED
