// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SITLGps.proto

#ifndef PROTOBUF_SITLGps_2eproto__INCLUDED
#define PROTOBUF_SITLGps_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace sensor_msgs {
namespace msgs {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_SITLGps_2eproto();
void protobuf_AssignDesc_SITLGps_2eproto();
void protobuf_ShutdownFile_SITLGps_2eproto();

class SITLGps;

// ===================================================================

class SITLGps : public ::google::protobuf::Message {
 public:
  SITLGps();
  virtual ~SITLGps();

  SITLGps(const SITLGps& from);

  inline SITLGps& operator=(const SITLGps& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SITLGps& default_instance();

  void Swap(SITLGps* other);

  // implements Message ----------------------------------------------

  SITLGps* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SITLGps& from);
  void MergeFrom(const SITLGps& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double time = 1;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 1;
  inline double time() const;
  inline void set_time(double value);

  // required double latitude_deg = 2;
  inline bool has_latitude_deg() const;
  inline void clear_latitude_deg();
  static const int kLatitudeDegFieldNumber = 2;
  inline double latitude_deg() const;
  inline void set_latitude_deg(double value);

  // required double longitude_deg = 3;
  inline bool has_longitude_deg() const;
  inline void clear_longitude_deg();
  static const int kLongitudeDegFieldNumber = 3;
  inline double longitude_deg() const;
  inline void set_longitude_deg(double value);

  // required double altitude = 4;
  inline bool has_altitude() const;
  inline void clear_altitude();
  static const int kAltitudeFieldNumber = 4;
  inline double altitude() const;
  inline void set_altitude(double value);

  // optional double eph = 5;
  inline bool has_eph() const;
  inline void clear_eph();
  static const int kEphFieldNumber = 5;
  inline double eph() const;
  inline void set_eph(double value);

  // optional double epv = 6;
  inline bool has_epv() const;
  inline void clear_epv();
  static const int kEpvFieldNumber = 6;
  inline double epv() const;
  inline void set_epv(double value);

  // optional double velocity = 7;
  inline bool has_velocity() const;
  inline void clear_velocity();
  static const int kVelocityFieldNumber = 7;
  inline double velocity() const;
  inline void set_velocity(double value);

  // optional double velocity_east = 8;
  inline bool has_velocity_east() const;
  inline void clear_velocity_east();
  static const int kVelocityEastFieldNumber = 8;
  inline double velocity_east() const;
  inline void set_velocity_east(double value);

  // optional double velocity_north = 9;
  inline bool has_velocity_north() const;
  inline void clear_velocity_north();
  static const int kVelocityNorthFieldNumber = 9;
  inline double velocity_north() const;
  inline void set_velocity_north(double value);

  // optional double velocity_up = 10;
  inline bool has_velocity_up() const;
  inline void clear_velocity_up();
  static const int kVelocityUpFieldNumber = 10;
  inline double velocity_up() const;
  inline void set_velocity_up(double value);

  // @@protoc_insertion_point(class_scope:sensor_msgs.msgs.SITLGps)
 private:
  inline void set_has_time();
  inline void clear_has_time();
  inline void set_has_latitude_deg();
  inline void clear_has_latitude_deg();
  inline void set_has_longitude_deg();
  inline void clear_has_longitude_deg();
  inline void set_has_altitude();
  inline void clear_has_altitude();
  inline void set_has_eph();
  inline void clear_has_eph();
  inline void set_has_epv();
  inline void clear_has_epv();
  inline void set_has_velocity();
  inline void clear_has_velocity();
  inline void set_has_velocity_east();
  inline void clear_has_velocity_east();
  inline void set_has_velocity_north();
  inline void clear_has_velocity_north();
  inline void set_has_velocity_up();
  inline void clear_has_velocity_up();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double time_;
  double latitude_deg_;
  double longitude_deg_;
  double altitude_;
  double eph_;
  double epv_;
  double velocity_;
  double velocity_east_;
  double velocity_north_;
  double velocity_up_;
  friend void  protobuf_AddDesc_SITLGps_2eproto();
  friend void protobuf_AssignDesc_SITLGps_2eproto();
  friend void protobuf_ShutdownFile_SITLGps_2eproto();

  void InitAsDefaultInstance();
  static SITLGps* default_instance_;
};
// ===================================================================


// ===================================================================

// SITLGps

// required double time = 1;
inline bool SITLGps::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SITLGps::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SITLGps::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SITLGps::clear_time() {
  time_ = 0;
  clear_has_time();
}
inline double SITLGps::time() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.SITLGps.time)
  return time_;
}
inline void SITLGps::set_time(double value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.SITLGps.time)
}

// required double latitude_deg = 2;
inline bool SITLGps::has_latitude_deg() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SITLGps::set_has_latitude_deg() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SITLGps::clear_has_latitude_deg() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SITLGps::clear_latitude_deg() {
  latitude_deg_ = 0;
  clear_has_latitude_deg();
}
inline double SITLGps::latitude_deg() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.SITLGps.latitude_deg)
  return latitude_deg_;
}
inline void SITLGps::set_latitude_deg(double value) {
  set_has_latitude_deg();
  latitude_deg_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.SITLGps.latitude_deg)
}

// required double longitude_deg = 3;
inline bool SITLGps::has_longitude_deg() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SITLGps::set_has_longitude_deg() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SITLGps::clear_has_longitude_deg() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SITLGps::clear_longitude_deg() {
  longitude_deg_ = 0;
  clear_has_longitude_deg();
}
inline double SITLGps::longitude_deg() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.SITLGps.longitude_deg)
  return longitude_deg_;
}
inline void SITLGps::set_longitude_deg(double value) {
  set_has_longitude_deg();
  longitude_deg_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.SITLGps.longitude_deg)
}

// required double altitude = 4;
inline bool SITLGps::has_altitude() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SITLGps::set_has_altitude() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SITLGps::clear_has_altitude() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SITLGps::clear_altitude() {
  altitude_ = 0;
  clear_has_altitude();
}
inline double SITLGps::altitude() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.SITLGps.altitude)
  return altitude_;
}
inline void SITLGps::set_altitude(double value) {
  set_has_altitude();
  altitude_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.SITLGps.altitude)
}

// optional double eph = 5;
inline bool SITLGps::has_eph() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SITLGps::set_has_eph() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SITLGps::clear_has_eph() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SITLGps::clear_eph() {
  eph_ = 0;
  clear_has_eph();
}
inline double SITLGps::eph() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.SITLGps.eph)
  return eph_;
}
inline void SITLGps::set_eph(double value) {
  set_has_eph();
  eph_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.SITLGps.eph)
}

// optional double epv = 6;
inline bool SITLGps::has_epv() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void SITLGps::set_has_epv() {
  _has_bits_[0] |= 0x00000020u;
}
inline void SITLGps::clear_has_epv() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void SITLGps::clear_epv() {
  epv_ = 0;
  clear_has_epv();
}
inline double SITLGps::epv() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.SITLGps.epv)
  return epv_;
}
inline void SITLGps::set_epv(double value) {
  set_has_epv();
  epv_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.SITLGps.epv)
}

// optional double velocity = 7;
inline bool SITLGps::has_velocity() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void SITLGps::set_has_velocity() {
  _has_bits_[0] |= 0x00000040u;
}
inline void SITLGps::clear_has_velocity() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void SITLGps::clear_velocity() {
  velocity_ = 0;
  clear_has_velocity();
}
inline double SITLGps::velocity() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.SITLGps.velocity)
  return velocity_;
}
inline void SITLGps::set_velocity(double value) {
  set_has_velocity();
  velocity_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.SITLGps.velocity)
}

// optional double velocity_east = 8;
inline bool SITLGps::has_velocity_east() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void SITLGps::set_has_velocity_east() {
  _has_bits_[0] |= 0x00000080u;
}
inline void SITLGps::clear_has_velocity_east() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void SITLGps::clear_velocity_east() {
  velocity_east_ = 0;
  clear_has_velocity_east();
}
inline double SITLGps::velocity_east() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.SITLGps.velocity_east)
  return velocity_east_;
}
inline void SITLGps::set_velocity_east(double value) {
  set_has_velocity_east();
  velocity_east_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.SITLGps.velocity_east)
}

// optional double velocity_north = 9;
inline bool SITLGps::has_velocity_north() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void SITLGps::set_has_velocity_north() {
  _has_bits_[0] |= 0x00000100u;
}
inline void SITLGps::clear_has_velocity_north() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void SITLGps::clear_velocity_north() {
  velocity_north_ = 0;
  clear_has_velocity_north();
}
inline double SITLGps::velocity_north() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.SITLGps.velocity_north)
  return velocity_north_;
}
inline void SITLGps::set_velocity_north(double value) {
  set_has_velocity_north();
  velocity_north_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.SITLGps.velocity_north)
}

// optional double velocity_up = 10;
inline bool SITLGps::has_velocity_up() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void SITLGps::set_has_velocity_up() {
  _has_bits_[0] |= 0x00000200u;
}
inline void SITLGps::clear_has_velocity_up() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void SITLGps::clear_velocity_up() {
  velocity_up_ = 0;
  clear_has_velocity_up();
}
inline double SITLGps::velocity_up() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.SITLGps.velocity_up)
  return velocity_up_;
}
inline void SITLGps::set_velocity_up(double value) {
  set_has_velocity_up();
  velocity_up_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.SITLGps.velocity_up)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace sensor_msgs

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_SITLGps_2eproto__INCLUDED
