# -*- coding: utf-8 -*-
# **********************************************************************
#
# Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.6.3
#
# <auto-generated>
#
# Generated from file `ardroneextra.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module jderobot
_M_jderobot = Ice.openModule('jderobot')
__name__ = 'jderobot'

if 'ArDroneExtra' not in _M_jderobot.__dict__:
    _M_jderobot.ArDroneExtra = Ice.createTempClass()
    class ArDroneExtra(Ice.Object):
        def __init__(self):
            if Ice.getType(self) == _M_jderobot.ArDroneExtra:
                raise RuntimeError('jderobot.ArDroneExtra is an abstract class')

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::jderobot::ArDroneExtra')

        def ice_id(self, current=None):
            return '::jderobot::ArDroneExtra'

        def ice_staticId():
            return '::jderobot::ArDroneExtra'
        ice_staticId = staticmethod(ice_staticId)

        def toggleCam(self, current=None):
            pass

        def land(self, current=None):
            pass

        def takeoff(self, current=None):
            pass

        def reset(self, current=None):
            pass

        def recordOnUsb(self, record, current=None):
            pass

        def ledAnimation(self, type, duration, req, current=None):
            pass

        def flightAnimation(self, type, duration, current=None):
            pass

        def flatTrim(self, current=None):
            pass

        def __str__(self):
            return IcePy.stringify(self, _M_jderobot._t_ArDroneExtra)

        __repr__ = __str__

    _M_jderobot.ArDroneExtraPrx = Ice.createTempClass()
    class ArDroneExtraPrx(Ice.ObjectPrx):

        def toggleCam(self, _ctx=None):
            return _M_jderobot.ArDroneExtra._op_toggleCam.invoke(self, ((), _ctx))

        def begin_toggleCam(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_jderobot.ArDroneExtra._op_toggleCam.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_toggleCam(self, _r):
            return _M_jderobot.ArDroneExtra._op_toggleCam.end(self, _r)

        def land(self, _ctx=None):
            return _M_jderobot.ArDroneExtra._op_land.invoke(self, ((), _ctx))

        def begin_land(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_jderobot.ArDroneExtra._op_land.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_land(self, _r):
            return _M_jderobot.ArDroneExtra._op_land.end(self, _r)

        def takeoff(self, _ctx=None):
            return _M_jderobot.ArDroneExtra._op_takeoff.invoke(self, ((), _ctx))

        def begin_takeoff(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_jderobot.ArDroneExtra._op_takeoff.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_takeoff(self, _r):
            return _M_jderobot.ArDroneExtra._op_takeoff.end(self, _r)

        def reset(self, _ctx=None):
            return _M_jderobot.ArDroneExtra._op_reset.invoke(self, ((), _ctx))

        def begin_reset(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_jderobot.ArDroneExtra._op_reset.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_reset(self, _r):
            return _M_jderobot.ArDroneExtra._op_reset.end(self, _r)

        def recordOnUsb(self, record, _ctx=None):
            return _M_jderobot.ArDroneExtra._op_recordOnUsb.invoke(self, ((record, ), _ctx))

        def begin_recordOnUsb(self, record, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_jderobot.ArDroneExtra._op_recordOnUsb.begin(self, ((record, ), _response, _ex, _sent, _ctx))

        def end_recordOnUsb(self, _r):
            return _M_jderobot.ArDroneExtra._op_recordOnUsb.end(self, _r)

        def ledAnimation(self, type, duration, req, _ctx=None):
            return _M_jderobot.ArDroneExtra._op_ledAnimation.invoke(self, ((type, duration, req), _ctx))

        def begin_ledAnimation(self, type, duration, req, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_jderobot.ArDroneExtra._op_ledAnimation.begin(self, ((type, duration, req), _response, _ex, _sent, _ctx))

        def end_ledAnimation(self, _r):
            return _M_jderobot.ArDroneExtra._op_ledAnimation.end(self, _r)

        def flightAnimation(self, type, duration, _ctx=None):
            return _M_jderobot.ArDroneExtra._op_flightAnimation.invoke(self, ((type, duration), _ctx))

        def begin_flightAnimation(self, type, duration, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_jderobot.ArDroneExtra._op_flightAnimation.begin(self, ((type, duration), _response, _ex, _sent, _ctx))

        def end_flightAnimation(self, _r):
            return _M_jderobot.ArDroneExtra._op_flightAnimation.end(self, _r)

        def flatTrim(self, _ctx=None):
            return _M_jderobot.ArDroneExtra._op_flatTrim.invoke(self, ((), _ctx))

        def begin_flatTrim(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_jderobot.ArDroneExtra._op_flatTrim.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_flatTrim(self, _r):
            return _M_jderobot.ArDroneExtra._op_flatTrim.end(self, _r)

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_jderobot.ArDroneExtraPrx.ice_checkedCast(proxy, '::jderobot::ArDroneExtra', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_jderobot.ArDroneExtraPrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

        def ice_staticId():
            return '::jderobot::ArDroneExtra'
        ice_staticId = staticmethod(ice_staticId)

    _M_jderobot._t_ArDroneExtraPrx = IcePy.defineProxy('::jderobot::ArDroneExtra', ArDroneExtraPrx)

    _M_jderobot._t_ArDroneExtra = IcePy.defineClass('::jderobot::ArDroneExtra', ArDroneExtra, -1, (), True, False, None, (), ())
    ArDroneExtra._ice_type = _M_jderobot._t_ArDroneExtra

    ArDroneExtra._op_toggleCam = IcePy.Operation('toggleCam', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), None, ())
    ArDroneExtra._op_land = IcePy.Operation('land', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), None, ())
    ArDroneExtra._op_takeoff = IcePy.Operation('takeoff', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), None, ())
    ArDroneExtra._op_reset = IcePy.Operation('reset', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), None, ())
    ArDroneExtra._op_recordOnUsb = IcePy.Operation('recordOnUsb', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_bool, False, 0),), (), None, ())
    ArDroneExtra._op_ledAnimation = IcePy.Operation('ledAnimation', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_int, False, 0), ((), IcePy._t_float, False, 0), ((), IcePy._t_float, False, 0)), (), None, ())
    ArDroneExtra._op_flightAnimation = IcePy.Operation('flightAnimation', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_int, False, 0), ((), IcePy._t_float, False, 0)), (), None, ())
    ArDroneExtra._op_flatTrim = IcePy.Operation('flatTrim', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), None, ())

    _M_jderobot.ArDroneExtra = ArDroneExtra
    del ArDroneExtra

    _M_jderobot.ArDroneExtraPrx = ArDroneExtraPrx
    del ArDroneExtraPrx

# End of module jderobot
