# -*- coding: utf-8 -*-
# **********************************************************************
#
# Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.6.3
#
# <auto-generated>
#
# Generated from file `kinectleds.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module jderobot
_M_jderobot = Ice.openModule('jderobot')
__name__ = 'jderobot'

if 'KinectLedsAvailable' not in _M_jderobot.__dict__:
    _M_jderobot.KinectLedsAvailable = Ice.createTempClass()
    class KinectLedsAvailable(Ice.EnumBase):

        def __init__(self, _n, _v):
            Ice.EnumBase.__init__(self, _n, _v)

        def valueOf(self, _n):
            if _n in self._enumerators:
                return self._enumerators[_n]
            return None
        valueOf = classmethod(valueOf)

    KinectLedsAvailable.OFF = KinectLedsAvailable("OFF", 0)
    KinectLedsAvailable.GREEN = KinectLedsAvailable("GREEN", 1)
    KinectLedsAvailable.RED = KinectLedsAvailable("RED", 2)
    KinectLedsAvailable.YELLOW = KinectLedsAvailable("YELLOW", 3)
    KinectLedsAvailable.BLINKGREEN = KinectLedsAvailable("BLINKGREEN", 4)
    KinectLedsAvailable.BLINKYELLOW = KinectLedsAvailable("BLINKYELLOW", 5)
    KinectLedsAvailable.BLINKRED = KinectLedsAvailable("BLINKRED", 6)
    KinectLedsAvailable._enumerators = { 0:KinectLedsAvailable.OFF, 1:KinectLedsAvailable.GREEN, 2:KinectLedsAvailable.RED, 3:KinectLedsAvailable.YELLOW, 4:KinectLedsAvailable.BLINKGREEN, 5:KinectLedsAvailable.BLINKYELLOW, 6:KinectLedsAvailable.BLINKRED }

    _M_jderobot._t_KinectLedsAvailable = IcePy.defineEnum('::jderobot::KinectLedsAvailable', KinectLedsAvailable, (), KinectLedsAvailable._enumerators)

    _M_jderobot.KinectLedsAvailable = KinectLedsAvailable
    del KinectLedsAvailable

if 'KinectLeds' not in _M_jderobot.__dict__:
    _M_jderobot.KinectLeds = Ice.createTempClass()
    class KinectLeds(Ice.Object):
        """
        Interface to the Kinect LEDS.
        """
        def __init__(self):
            if Ice.getType(self) == _M_jderobot.KinectLeds:
                raise RuntimeError('jderobot.KinectLeds is an abstract class')

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::jderobot::KinectLeds')

        def ice_id(self, current=None):
            return '::jderobot::KinectLeds'

        def ice_staticId():
            return '::jderobot::KinectLeds'
        ice_staticId = staticmethod(ice_staticId)

        def setLedActive(self, led, current=None):
            pass

        def __str__(self):
            return IcePy.stringify(self, _M_jderobot._t_KinectLeds)

        __repr__ = __str__

    _M_jderobot.KinectLedsPrx = Ice.createTempClass()
    class KinectLedsPrx(Ice.ObjectPrx):

        def setLedActive(self, led, _ctx=None):
            return _M_jderobot.KinectLeds._op_setLedActive.invoke(self, ((led, ), _ctx))

        def begin_setLedActive(self, led, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_jderobot.KinectLeds._op_setLedActive.begin(self, ((led, ), _response, _ex, _sent, _ctx))

        def end_setLedActive(self, _r):
            return _M_jderobot.KinectLeds._op_setLedActive.end(self, _r)

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_jderobot.KinectLedsPrx.ice_checkedCast(proxy, '::jderobot::KinectLeds', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_jderobot.KinectLedsPrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

        def ice_staticId():
            return '::jderobot::KinectLeds'
        ice_staticId = staticmethod(ice_staticId)

    _M_jderobot._t_KinectLedsPrx = IcePy.defineProxy('::jderobot::KinectLeds', KinectLedsPrx)

    _M_jderobot._t_KinectLeds = IcePy.defineClass('::jderobot::KinectLeds', KinectLeds, -1, (), True, False, None, (), ())
    KinectLeds._ice_type = _M_jderobot._t_KinectLeds

    KinectLeds._op_setLedActive = IcePy.Operation('setLedActive', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_jderobot._t_KinectLedsAvailable, False, 0),), (), None, ())

    _M_jderobot.KinectLeds = KinectLeds
    del KinectLeds

    _M_jderobot.KinectLedsPrx = KinectLedsPrx
    del KinectLedsPrx

# End of module jderobot
