# -*- coding: utf-8 -*-
# **********************************************************************
#
# Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.6.3
#
# <auto-generated>
#
# Generated from file `pose3dmotors.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module jderobot
_M_jderobot = Ice.openModule('jderobot')
__name__ = 'jderobot'

if 'Time' not in _M_jderobot.__dict__:
    _M_jderobot.Time = Ice.createTempClass()
    class Time(object):
        def __init__(self, seconds=0, useconds=0):
            self.seconds = seconds
            self.useconds = useconds

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.seconds)
            _h = 5 * _h + Ice.getHash(self.useconds)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_jderobot.Time):
                return NotImplemented
            else:
                if self.seconds is None or other.seconds is None:
                    if self.seconds != other.seconds:
                        return (-1 if self.seconds is None else 1)
                else:
                    if self.seconds < other.seconds:
                        return -1
                    elif self.seconds > other.seconds:
                        return 1
                if self.useconds is None or other.useconds is None:
                    if self.useconds != other.useconds:
                        return (-1 if self.useconds is None else 1)
                else:
                    if self.useconds < other.useconds:
                        return -1
                    elif self.useconds > other.useconds:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_jderobot._t_Time)

        __repr__ = __str__

    _M_jderobot._t_Time = IcePy.defineStruct('::jderobot::Time', Time, (), (
        ('seconds', (), IcePy._t_long),
        ('useconds', (), IcePy._t_long)
    ))

    _M_jderobot.Time = Time
    del Time

# End of module jderobot

# Start of module jderobot
__name__ = 'jderobot'

if 'JderobotException' not in _M_jderobot.__dict__:
    _M_jderobot.JderobotException = Ice.createTempClass()
    class JderobotException(Ice.UserException):
        def __init__(self, what=''):
            self.what = what

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_name = 'jderobot::JderobotException'

    _M_jderobot._t_JderobotException = IcePy.defineException('::jderobot::JderobotException', JderobotException, (), False, None, (('what', (), IcePy._t_string, False, 0),))
    JderobotException._ice_type = _M_jderobot._t_JderobotException

    _M_jderobot.JderobotException = JderobotException
    del JderobotException

if 'ConfigurationNotExistException' not in _M_jderobot.__dict__:
    _M_jderobot.ConfigurationNotExistException = Ice.createTempClass()
    class ConfigurationNotExistException(_M_jderobot.JderobotException):
        def __init__(self, what=''):
            _M_jderobot.JderobotException.__init__(self, what)

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_name = 'jderobot::ConfigurationNotExistException'

    _M_jderobot._t_ConfigurationNotExistException = IcePy.defineException('::jderobot::ConfigurationNotExistException', ConfigurationNotExistException, (), False, _M_jderobot._t_JderobotException, ())
    ConfigurationNotExistException._ice_type = _M_jderobot._t_ConfigurationNotExistException

    _M_jderobot.ConfigurationNotExistException = ConfigurationNotExistException
    del ConfigurationNotExistException

if 'DataNotExistException' not in _M_jderobot.__dict__:
    _M_jderobot.DataNotExistException = Ice.createTempClass()
    class DataNotExistException(_M_jderobot.JderobotException):
        def __init__(self, what=''):
            _M_jderobot.JderobotException.__init__(self, what)

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_name = 'jderobot::DataNotExistException'

    _M_jderobot._t_DataNotExistException = IcePy.defineException('::jderobot::DataNotExistException', DataNotExistException, (), False, _M_jderobot._t_JderobotException, ())
    DataNotExistException._ice_type = _M_jderobot._t_DataNotExistException

    _M_jderobot.DataNotExistException = DataNotExistException
    del DataNotExistException

if 'HardwareFailedException' not in _M_jderobot.__dict__:
    _M_jderobot.HardwareFailedException = Ice.createTempClass()
    class HardwareFailedException(_M_jderobot.JderobotException):
        def __init__(self, what=''):
            _M_jderobot.JderobotException.__init__(self, what)

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_name = 'jderobot::HardwareFailedException'

    _M_jderobot._t_HardwareFailedException = IcePy.defineException('::jderobot::HardwareFailedException', HardwareFailedException, (), False, _M_jderobot._t_JderobotException, ())
    HardwareFailedException._ice_type = _M_jderobot._t_HardwareFailedException

    _M_jderobot.HardwareFailedException = HardwareFailedException
    del HardwareFailedException

if 'NoTopicException' not in _M_jderobot.__dict__:
    _M_jderobot.NoTopicException = Ice.createTempClass()
    class NoTopicException(_M_jderobot.JderobotException):
        def __init__(self, what=''):
            _M_jderobot.JderobotException.__init__(self, what)

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_name = 'jderobot::NoTopicException'

    _M_jderobot._t_NoTopicException = IcePy.defineException('::jderobot::NoTopicException', NoTopicException, (), False, _M_jderobot._t_JderobotException, ())
    NoTopicException._ice_type = _M_jderobot._t_NoTopicException

    _M_jderobot.NoTopicException = NoTopicException
    del NoTopicException

if 'SubscriptionFailedException' not in _M_jderobot.__dict__:
    _M_jderobot.SubscriptionFailedException = Ice.createTempClass()
    class SubscriptionFailedException(_M_jderobot.JderobotException):
        def __init__(self, what=''):
            _M_jderobot.JderobotException.__init__(self, what)

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_name = 'jderobot::SubscriptionFailedException'

    _M_jderobot._t_SubscriptionFailedException = IcePy.defineException('::jderobot::SubscriptionFailedException', SubscriptionFailedException, (), False, _M_jderobot._t_JderobotException, ())
    SubscriptionFailedException._ice_type = _M_jderobot._t_SubscriptionFailedException

    _M_jderobot.SubscriptionFailedException = SubscriptionFailedException
    del SubscriptionFailedException

if 'SubscriptionPushFailedException' not in _M_jderobot.__dict__:
    _M_jderobot.SubscriptionPushFailedException = Ice.createTempClass()
    class SubscriptionPushFailedException(_M_jderobot.JderobotException):
        def __init__(self, what=''):
            _M_jderobot.JderobotException.__init__(self, what)

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_name = 'jderobot::SubscriptionPushFailedException'

    _M_jderobot._t_SubscriptionPushFailedException = IcePy.defineException('::jderobot::SubscriptionPushFailedException', SubscriptionPushFailedException, (), False, _M_jderobot._t_JderobotException, ())
    SubscriptionPushFailedException._ice_type = _M_jderobot._t_SubscriptionPushFailedException

    _M_jderobot.SubscriptionPushFailedException = SubscriptionPushFailedException
    del SubscriptionPushFailedException

# End of module jderobot

# Start of module jderobot
__name__ = 'jderobot'

if '_t_ByteSeq' not in _M_jderobot.__dict__:
    _M_jderobot._t_ByteSeq = IcePy.defineSequence('::jderobot::ByteSeq', (), IcePy._t_byte)

if '_t_IntSeq' not in _M_jderobot.__dict__:
    _M_jderobot._t_IntSeq = IcePy.defineSequence('::jderobot::IntSeq', (), IcePy._t_int)

if '_t_seqFloat' not in _M_jderobot.__dict__:
    _M_jderobot._t_seqFloat = IcePy.defineSequence('::jderobot::seqFloat', (), IcePy._t_float)

# End of module jderobot

# Start of module jderobot
__name__ = 'jderobot'

# End of module jderobot

# Start of module jderobot
__name__ = 'jderobot'

if 'Pose3DMotorsData' not in _M_jderobot.__dict__:
    _M_jderobot.Pose3DMotorsData = Ice.createTempClass()
    class Pose3DMotorsData(Ice.Object):
        """
        Pose3DMotorsData a class that contains the pantilt data
        """
        def __init__(self, x=0.0, y=0.0, z=0.0, pan=0.0, tilt=0.0, roll=0.0, panSpeed=0.0, tiltSpeed=0.0):
            self.x = x
            self.y = y
            self.z = z
            self.pan = pan
            self.tilt = tilt
            self.roll = roll
            self.panSpeed = panSpeed
            self.tiltSpeed = tiltSpeed

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::jderobot::Pose3DMotorsData')

        def ice_id(self, current=None):
            return '::jderobot::Pose3DMotorsData'

        def ice_staticId():
            return '::jderobot::Pose3DMotorsData'
        ice_staticId = staticmethod(ice_staticId)

        def __str__(self):
            return IcePy.stringify(self, _M_jderobot._t_Pose3DMotorsData)

        __repr__ = __str__

    _M_jderobot.Pose3DMotorsDataPrx = Ice.createTempClass()
    class Pose3DMotorsDataPrx(Ice.ObjectPrx):

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_jderobot.Pose3DMotorsDataPrx.ice_checkedCast(proxy, '::jderobot::Pose3DMotorsData', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_jderobot.Pose3DMotorsDataPrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

        def ice_staticId():
            return '::jderobot::Pose3DMotorsData'
        ice_staticId = staticmethod(ice_staticId)

    _M_jderobot._t_Pose3DMotorsDataPrx = IcePy.defineProxy('::jderobot::Pose3DMotorsData', Pose3DMotorsDataPrx)

    _M_jderobot._t_Pose3DMotorsData = IcePy.defineClass('::jderobot::Pose3DMotorsData', Pose3DMotorsData, -1, (), False, False, None, (), (
        ('x', (), IcePy._t_float, False, 0),
        ('y', (), IcePy._t_float, False, 0),
        ('z', (), IcePy._t_float, False, 0),
        ('pan', (), IcePy._t_float, False, 0),
        ('tilt', (), IcePy._t_float, False, 0),
        ('roll', (), IcePy._t_float, False, 0),
        ('panSpeed', (), IcePy._t_float, False, 0),
        ('tiltSpeed', (), IcePy._t_float, False, 0)
    ))
    Pose3DMotorsData._ice_type = _M_jderobot._t_Pose3DMotorsData

    _M_jderobot.Pose3DMotorsData = Pose3DMotorsData
    del Pose3DMotorsData

    _M_jderobot.Pose3DMotorsDataPrx = Pose3DMotorsDataPrx
    del Pose3DMotorsDataPrx

if 'Pose3DMotorsParams' not in _M_jderobot.__dict__:
    _M_jderobot.Pose3DMotorsParams = Ice.createTempClass()
    class Pose3DMotorsParams(Ice.Object):
        """
        Pose3DMotorsParams a class that contains the motors parametres.
        """
        def __init__(self, maxPan=0.0, minPan=0.0, maxTilt=0.0, minTilt=0.0, maxPanSpeed=0.0, maxTiltSpeed=0.0):
            self.maxPan = maxPan
            self.minPan = minPan
            self.maxTilt = maxTilt
            self.minTilt = minTilt
            self.maxPanSpeed = maxPanSpeed
            self.maxTiltSpeed = maxTiltSpeed

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::jderobot::Pose3DMotorsParams')

        def ice_id(self, current=None):
            return '::jderobot::Pose3DMotorsParams'

        def ice_staticId():
            return '::jderobot::Pose3DMotorsParams'
        ice_staticId = staticmethod(ice_staticId)

        def __str__(self):
            return IcePy.stringify(self, _M_jderobot._t_Pose3DMotorsParams)

        __repr__ = __str__

    _M_jderobot.Pose3DMotorsParamsPrx = Ice.createTempClass()
    class Pose3DMotorsParamsPrx(Ice.ObjectPrx):

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_jderobot.Pose3DMotorsParamsPrx.ice_checkedCast(proxy, '::jderobot::Pose3DMotorsParams', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_jderobot.Pose3DMotorsParamsPrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

        def ice_staticId():
            return '::jderobot::Pose3DMotorsParams'
        ice_staticId = staticmethod(ice_staticId)

    _M_jderobot._t_Pose3DMotorsParamsPrx = IcePy.defineProxy('::jderobot::Pose3DMotorsParams', Pose3DMotorsParamsPrx)

    _M_jderobot._t_Pose3DMotorsParams = IcePy.defineClass('::jderobot::Pose3DMotorsParams', Pose3DMotorsParams, -1, (), False, False, None, (), (
        ('maxPan', (), IcePy._t_float, False, 0),
        ('minPan', (), IcePy._t_float, False, 0),
        ('maxTilt', (), IcePy._t_float, False, 0),
        ('minTilt', (), IcePy._t_float, False, 0),
        ('maxPanSpeed', (), IcePy._t_float, False, 0),
        ('maxTiltSpeed', (), IcePy._t_float, False, 0)
    ))
    Pose3DMotorsParams._ice_type = _M_jderobot._t_Pose3DMotorsParams

    _M_jderobot.Pose3DMotorsParams = Pose3DMotorsParams
    del Pose3DMotorsParams

    _M_jderobot.Pose3DMotorsParamsPrx = Pose3DMotorsParamsPrx
    del Pose3DMotorsParamsPrx

if 'Pose3DMotors' not in _M_jderobot.__dict__:
    _M_jderobot.Pose3DMotors = Ice.createTempClass()
    class Pose3DMotors(Ice.Object):
        """
        Interface to the Pose3DMotors Actuators interaction.
        """
        def __init__(self):
            if Ice.getType(self) == _M_jderobot.Pose3DMotors:
                raise RuntimeError('jderobot.Pose3DMotors is an abstract class')

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::jderobot::Pose3DMotors')

        def ice_id(self, current=None):
            return '::jderobot::Pose3DMotors'

        def ice_staticId():
            return '::jderobot::Pose3DMotors'
        ice_staticId = staticmethod(ice_staticId)

        def setPose3DMotorsData(self, data, current=None):
            pass

        def getPose3DMotorsData(self, current=None):
            pass

        def getPose3DMotorsParams(self, current=None):
            pass

        def __str__(self):
            return IcePy.stringify(self, _M_jderobot._t_Pose3DMotors)

        __repr__ = __str__

    _M_jderobot.Pose3DMotorsPrx = Ice.createTempClass()
    class Pose3DMotorsPrx(Ice.ObjectPrx):

        def setPose3DMotorsData(self, data, _ctx=None):
            return _M_jderobot.Pose3DMotors._op_setPose3DMotorsData.invoke(self, ((data, ), _ctx))

        def begin_setPose3DMotorsData(self, data, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_jderobot.Pose3DMotors._op_setPose3DMotorsData.begin(self, ((data, ), _response, _ex, _sent, _ctx))

        def end_setPose3DMotorsData(self, _r):
            return _M_jderobot.Pose3DMotors._op_setPose3DMotorsData.end(self, _r)

        def getPose3DMotorsData(self, _ctx=None):
            return _M_jderobot.Pose3DMotors._op_getPose3DMotorsData.invoke(self, ((), _ctx))

        def begin_getPose3DMotorsData(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_jderobot.Pose3DMotors._op_getPose3DMotorsData.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getPose3DMotorsData(self, _r):
            return _M_jderobot.Pose3DMotors._op_getPose3DMotorsData.end(self, _r)

        def getPose3DMotorsParams(self, _ctx=None):
            return _M_jderobot.Pose3DMotors._op_getPose3DMotorsParams.invoke(self, ((), _ctx))

        def begin_getPose3DMotorsParams(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_jderobot.Pose3DMotors._op_getPose3DMotorsParams.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getPose3DMotorsParams(self, _r):
            return _M_jderobot.Pose3DMotors._op_getPose3DMotorsParams.end(self, _r)

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_jderobot.Pose3DMotorsPrx.ice_checkedCast(proxy, '::jderobot::Pose3DMotors', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_jderobot.Pose3DMotorsPrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

        def ice_staticId():
            return '::jderobot::Pose3DMotors'
        ice_staticId = staticmethod(ice_staticId)

    _M_jderobot._t_Pose3DMotorsPrx = IcePy.defineProxy('::jderobot::Pose3DMotors', Pose3DMotorsPrx)

    _M_jderobot._t_Pose3DMotors = IcePy.defineClass('::jderobot::Pose3DMotors', Pose3DMotors, -1, (), True, False, None, (), ())
    Pose3DMotors._ice_type = _M_jderobot._t_Pose3DMotors

    Pose3DMotors._op_setPose3DMotorsData = IcePy.Operation('setPose3DMotorsData', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_jderobot._t_Pose3DMotorsData, False, 0),), (), ((), IcePy._t_int, False, 0), ())
    Pose3DMotors._op_getPose3DMotorsData = IcePy.Operation('getPose3DMotorsData', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (), (), ((), _M_jderobot._t_Pose3DMotorsData, False, 0), ())
    Pose3DMotors._op_getPose3DMotorsParams = IcePy.Operation('getPose3DMotorsParams', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (), (), ((), _M_jderobot._t_Pose3DMotorsParams, False, 0), ())

    _M_jderobot.Pose3DMotors = Pose3DMotors
    del Pose3DMotors

    _M_jderobot.Pose3DMotorsPrx = Pose3DMotorsPrx
    del Pose3DMotorsPrx

# End of module jderobot
