# -*- coding: utf-8 -*-
# **********************************************************************
#
# Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.6.3
#
# <auto-generated>
#
# Generated from file `pose3dencoders.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module jderobot
_M_jderobot = Ice.openModule('jderobot')
__name__ = 'jderobot'

if 'Time' not in _M_jderobot.__dict__:
    _M_jderobot.Time = Ice.createTempClass()
    class Time(object):
        def __init__(self, seconds=0, useconds=0):
            self.seconds = seconds
            self.useconds = useconds

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.seconds)
            _h = 5 * _h + Ice.getHash(self.useconds)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_jderobot.Time):
                return NotImplemented
            else:
                if self.seconds is None or other.seconds is None:
                    if self.seconds != other.seconds:
                        return (-1 if self.seconds is None else 1)
                else:
                    if self.seconds < other.seconds:
                        return -1
                    elif self.seconds > other.seconds:
                        return 1
                if self.useconds is None or other.useconds is None:
                    if self.useconds != other.useconds:
                        return (-1 if self.useconds is None else 1)
                else:
                    if self.useconds < other.useconds:
                        return -1
                    elif self.useconds > other.useconds:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_jderobot._t_Time)

        __repr__ = __str__

    _M_jderobot._t_Time = IcePy.defineStruct('::jderobot::Time', Time, (), (
        ('seconds', (), IcePy._t_long),
        ('useconds', (), IcePy._t_long)
    ))

    _M_jderobot.Time = Time
    del Time

# End of module jderobot

# Start of module jderobot
__name__ = 'jderobot'

if 'JderobotException' not in _M_jderobot.__dict__:
    _M_jderobot.JderobotException = Ice.createTempClass()
    class JderobotException(Ice.UserException):
        def __init__(self, what=''):
            self.what = what

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_name = 'jderobot::JderobotException'

    _M_jderobot._t_JderobotException = IcePy.defineException('::jderobot::JderobotException', JderobotException, (), False, None, (('what', (), IcePy._t_string, False, 0),))
    JderobotException._ice_type = _M_jderobot._t_JderobotException

    _M_jderobot.JderobotException = JderobotException
    del JderobotException

if 'ConfigurationNotExistException' not in _M_jderobot.__dict__:
    _M_jderobot.ConfigurationNotExistException = Ice.createTempClass()
    class ConfigurationNotExistException(_M_jderobot.JderobotException):
        def __init__(self, what=''):
            _M_jderobot.JderobotException.__init__(self, what)

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_name = 'jderobot::ConfigurationNotExistException'

    _M_jderobot._t_ConfigurationNotExistException = IcePy.defineException('::jderobot::ConfigurationNotExistException', ConfigurationNotExistException, (), False, _M_jderobot._t_JderobotException, ())
    ConfigurationNotExistException._ice_type = _M_jderobot._t_ConfigurationNotExistException

    _M_jderobot.ConfigurationNotExistException = ConfigurationNotExistException
    del ConfigurationNotExistException

if 'DataNotExistException' not in _M_jderobot.__dict__:
    _M_jderobot.DataNotExistException = Ice.createTempClass()
    class DataNotExistException(_M_jderobot.JderobotException):
        def __init__(self, what=''):
            _M_jderobot.JderobotException.__init__(self, what)

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_name = 'jderobot::DataNotExistException'

    _M_jderobot._t_DataNotExistException = IcePy.defineException('::jderobot::DataNotExistException', DataNotExistException, (), False, _M_jderobot._t_JderobotException, ())
    DataNotExistException._ice_type = _M_jderobot._t_DataNotExistException

    _M_jderobot.DataNotExistException = DataNotExistException
    del DataNotExistException

if 'HardwareFailedException' not in _M_jderobot.__dict__:
    _M_jderobot.HardwareFailedException = Ice.createTempClass()
    class HardwareFailedException(_M_jderobot.JderobotException):
        def __init__(self, what=''):
            _M_jderobot.JderobotException.__init__(self, what)

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_name = 'jderobot::HardwareFailedException'

    _M_jderobot._t_HardwareFailedException = IcePy.defineException('::jderobot::HardwareFailedException', HardwareFailedException, (), False, _M_jderobot._t_JderobotException, ())
    HardwareFailedException._ice_type = _M_jderobot._t_HardwareFailedException

    _M_jderobot.HardwareFailedException = HardwareFailedException
    del HardwareFailedException

if 'NoTopicException' not in _M_jderobot.__dict__:
    _M_jderobot.NoTopicException = Ice.createTempClass()
    class NoTopicException(_M_jderobot.JderobotException):
        def __init__(self, what=''):
            _M_jderobot.JderobotException.__init__(self, what)

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_name = 'jderobot::NoTopicException'

    _M_jderobot._t_NoTopicException = IcePy.defineException('::jderobot::NoTopicException', NoTopicException, (), False, _M_jderobot._t_JderobotException, ())
    NoTopicException._ice_type = _M_jderobot._t_NoTopicException

    _M_jderobot.NoTopicException = NoTopicException
    del NoTopicException

if 'SubscriptionFailedException' not in _M_jderobot.__dict__:
    _M_jderobot.SubscriptionFailedException = Ice.createTempClass()
    class SubscriptionFailedException(_M_jderobot.JderobotException):
        def __init__(self, what=''):
            _M_jderobot.JderobotException.__init__(self, what)

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_name = 'jderobot::SubscriptionFailedException'

    _M_jderobot._t_SubscriptionFailedException = IcePy.defineException('::jderobot::SubscriptionFailedException', SubscriptionFailedException, (), False, _M_jderobot._t_JderobotException, ())
    SubscriptionFailedException._ice_type = _M_jderobot._t_SubscriptionFailedException

    _M_jderobot.SubscriptionFailedException = SubscriptionFailedException
    del SubscriptionFailedException

if 'SubscriptionPushFailedException' not in _M_jderobot.__dict__:
    _M_jderobot.SubscriptionPushFailedException = Ice.createTempClass()
    class SubscriptionPushFailedException(_M_jderobot.JderobotException):
        def __init__(self, what=''):
            _M_jderobot.JderobotException.__init__(self, what)

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_name = 'jderobot::SubscriptionPushFailedException'

    _M_jderobot._t_SubscriptionPushFailedException = IcePy.defineException('::jderobot::SubscriptionPushFailedException', SubscriptionPushFailedException, (), False, _M_jderobot._t_JderobotException, ())
    SubscriptionPushFailedException._ice_type = _M_jderobot._t_SubscriptionPushFailedException

    _M_jderobot.SubscriptionPushFailedException = SubscriptionPushFailedException
    del SubscriptionPushFailedException

# End of module jderobot

# Start of module jderobot
__name__ = 'jderobot'

if '_t_ByteSeq' not in _M_jderobot.__dict__:
    _M_jderobot._t_ByteSeq = IcePy.defineSequence('::jderobot::ByteSeq', (), IcePy._t_byte)

if '_t_IntSeq' not in _M_jderobot.__dict__:
    _M_jderobot._t_IntSeq = IcePy.defineSequence('::jderobot::IntSeq', (), IcePy._t_int)

if '_t_seqFloat' not in _M_jderobot.__dict__:
    _M_jderobot._t_seqFloat = IcePy.defineSequence('::jderobot::seqFloat', (), IcePy._t_float)

# End of module jderobot

# Start of module jderobot
__name__ = 'jderobot'

# End of module jderobot

# Start of module jderobot
__name__ = 'jderobot'

if 'Pose3DEncodersData' not in _M_jderobot.__dict__:
    _M_jderobot.Pose3DEncodersData = Ice.createTempClass()
    class Pose3DEncodersData(Ice.Object):
        """
        ptencoders dat information
        """
        def __init__(self, x=0.0, y=0.0, z=0.0, pan=0.0, tilt=0.0, roll=0.0, clock=0, maxPan=0.0, maxTilt=0.0, minPan=0.0, minTilt=0.0):
            self.x = x
            self.y = y
            self.z = z
            self.pan = pan
            self.tilt = tilt
            self.roll = roll
            self.clock = clock
            self.maxPan = maxPan
            self.maxTilt = maxTilt
            self.minPan = minPan
            self.minTilt = minTilt

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::jderobot::Pose3DEncodersData')

        def ice_id(self, current=None):
            return '::jderobot::Pose3DEncodersData'

        def ice_staticId():
            return '::jderobot::Pose3DEncodersData'
        ice_staticId = staticmethod(ice_staticId)

        def __str__(self):
            return IcePy.stringify(self, _M_jderobot._t_Pose3DEncodersData)

        __repr__ = __str__

    _M_jderobot.Pose3DEncodersDataPrx = Ice.createTempClass()
    class Pose3DEncodersDataPrx(Ice.ObjectPrx):

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_jderobot.Pose3DEncodersDataPrx.ice_checkedCast(proxy, '::jderobot::Pose3DEncodersData', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_jderobot.Pose3DEncodersDataPrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

        def ice_staticId():
            return '::jderobot::Pose3DEncodersData'
        ice_staticId = staticmethod(ice_staticId)

    _M_jderobot._t_Pose3DEncodersDataPrx = IcePy.defineProxy('::jderobot::Pose3DEncodersData', Pose3DEncodersDataPrx)

    _M_jderobot._t_Pose3DEncodersData = IcePy.defineClass('::jderobot::Pose3DEncodersData', Pose3DEncodersData, -1, (), False, False, None, (), (
        ('x', (), IcePy._t_float, False, 0),
        ('y', (), IcePy._t_float, False, 0),
        ('z', (), IcePy._t_float, False, 0),
        ('pan', (), IcePy._t_float, False, 0),
        ('tilt', (), IcePy._t_float, False, 0),
        ('roll', (), IcePy._t_float, False, 0),
        ('clock', (), IcePy._t_int, False, 0),
        ('maxPan', (), IcePy._t_float, False, 0),
        ('maxTilt', (), IcePy._t_float, False, 0),
        ('minPan', (), IcePy._t_float, False, 0),
        ('minTilt', (), IcePy._t_float, False, 0)
    ))
    Pose3DEncodersData._ice_type = _M_jderobot._t_Pose3DEncodersData

    _M_jderobot.Pose3DEncodersData = Pose3DEncodersData
    del Pose3DEncodersData

    _M_jderobot.Pose3DEncodersDataPrx = Pose3DEncodersDataPrx
    del Pose3DEncodersDataPrx

if 'Pose3DEncoders' not in _M_jderobot.__dict__:
    _M_jderobot.Pose3DEncoders = Ice.createTempClass()
    class Pose3DEncoders(Ice.Object):
        """
        Interface to the ptencoders sensor.
        """
        def __init__(self):
            if Ice.getType(self) == _M_jderobot.Pose3DEncoders:
                raise RuntimeError('jderobot.Pose3DEncoders is an abstract class')

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::jderobot::Pose3DEncoders')

        def ice_id(self, current=None):
            return '::jderobot::Pose3DEncoders'

        def ice_staticId():
            return '::jderobot::Pose3DEncoders'
        ice_staticId = staticmethod(ice_staticId)

        def getPose3DEncodersData(self, current=None):
            pass

        def __str__(self):
            return IcePy.stringify(self, _M_jderobot._t_Pose3DEncoders)

        __repr__ = __str__

    _M_jderobot.Pose3DEncodersPrx = Ice.createTempClass()
    class Pose3DEncodersPrx(Ice.ObjectPrx):

        def getPose3DEncodersData(self, _ctx=None):
            return _M_jderobot.Pose3DEncoders._op_getPose3DEncodersData.invoke(self, ((), _ctx))

        def begin_getPose3DEncodersData(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_jderobot.Pose3DEncoders._op_getPose3DEncodersData.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getPose3DEncodersData(self, _r):
            return _M_jderobot.Pose3DEncoders._op_getPose3DEncodersData.end(self, _r)

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_jderobot.Pose3DEncodersPrx.ice_checkedCast(proxy, '::jderobot::Pose3DEncoders', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_jderobot.Pose3DEncodersPrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

        def ice_staticId():
            return '::jderobot::Pose3DEncoders'
        ice_staticId = staticmethod(ice_staticId)

    _M_jderobot._t_Pose3DEncodersPrx = IcePy.defineProxy('::jderobot::Pose3DEncoders', Pose3DEncodersPrx)

    _M_jderobot._t_Pose3DEncoders = IcePy.defineClass('::jderobot::Pose3DEncoders', Pose3DEncoders, -1, (), True, False, None, (), ())
    Pose3DEncoders._ice_type = _M_jderobot._t_Pose3DEncoders

    Pose3DEncoders._op_getPose3DEncodersData = IcePy.Operation('getPose3DEncodersData', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (), (), ((), _M_jderobot._t_Pose3DEncodersData, False, 0), ())

    _M_jderobot.Pose3DEncoders = Pose3DEncoders
    del Pose3DEncoders

    _M_jderobot.Pose3DEncodersPrx = Pose3DEncodersPrx
    del Pose3DEncodersPrx

# End of module jderobot
