// **********************************************************************
//
// Copyright (c) 2003-2014 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ardroneextra.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(global, r)
{
    var require = typeof(r) === "function" ? r : function(){};
    require("Ice/Object");
    require("Ice/ObjectPrx");
    require("Ice/Operation");
    require("Ice/Long");
    require("Ice/HashMap");
    require("Ice/HashUtil");
    require("Ice/ArrayUtil");
    require("Ice/StreamHelpers");
    
    var Ice = global.Ice || {};
    var jderobot = global.jderobot ||  {};

    jderobot.ArDroneExtra = Slice.defineObject(
        undefined,
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::jderobot::ArDroneExtra"
        ],
        -1, undefined, undefined, false);

    jderobot.ArDroneExtraPrx = Slice.defineProxy(Ice.ObjectPrx, jderobot.ArDroneExtra.ice_staticId, undefined);

    Slice.defineOperations(jderobot.ArDroneExtra, jderobot.ArDroneExtraPrx,
    {
        "toggleCam": [, , , , , , , , , , ],
        "land": [, , , , , , , , , , ],
        "takeoff": [, , , , , , , , , , ],
        "reset": [, , , , , , , , , , ],
        "recordOnUsb": [, , , , , , [[1]], , , , ],
        "ledAnimation": [, , , , , , [[3], [5], [5]], , , , ],
        "flightAnimation": [, , , , , , [[3], [5]], , , , ],
        "flatTrim": [, , , , , , , , , , ]
    });
    global.jderobot = jderobot;
}
(typeof (global) === "undefined" ? window : global, typeof (require) === "undefined" ? undefined : require));
