// **********************************************************************
//
// Copyright (c) 2003-2014 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ptencoders.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(global, r)
{
    var require = typeof(r) === "function" ? r : function(){};
    require("Ice/Object");
    require("Ice/ObjectPrx");
    require("Ice/Operation");
    require("Ice/Long");
    require("Ice/HashMap");
    require("Ice/HashUtil");
    require("Ice/ArrayUtil");
    require("Ice/StreamHelpers");
    
    var Ice = global.Ice || {};
    require("common");
    
    var jderobot = global.jderobot || {};

    /**
     * ptencoders dat information 
     **/
    jderobot.PTEncodersData = Slice.defineObject(
        function(panAngle, tiltAngle, clock)
        {
            Ice.Object.call(this);
            this.panAngle = panAngle !== undefined ? panAngle : 0.0;
            this.tiltAngle = tiltAngle !== undefined ? tiltAngle : 0.0;
            this.clock = clock !== undefined ? clock : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::jderobot::PTEncodersData"
        ],
        -1,
        function(__os)
        {
            __os.writeFloat(this.panAngle);
            __os.writeFloat(this.tiltAngle);
            __os.writeInt(this.clock);
        },
        function(__is)
        {
            this.panAngle = __is.readFloat();
            this.tiltAngle = __is.readFloat();
            this.clock = __is.readInt();
        },
        false);

    jderobot.PTEncodersDataPrx = Slice.defineProxy(Ice.ObjectPrx, jderobot.PTEncodersData.ice_staticId, undefined);

    Slice.defineOperations(jderobot.PTEncodersData, jderobot.PTEncodersDataPrx);

    /**
     * Interface to the ptencoders sensor.
     **/
    jderobot.PTEncoders = Slice.defineObject(
        undefined,
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::jderobot::PTEncoders"
        ],
        -1, undefined, undefined, false);

    jderobot.PTEncodersPrx = Slice.defineProxy(Ice.ObjectPrx, jderobot.PTEncoders.ice_staticId, undefined);

    Slice.defineOperations(jderobot.PTEncoders, jderobot.PTEncodersPrx,
    {
        "getPTEncodersData": [, 2, 2, , , ["jderobot.PTEncodersData", true], , , , , true]
    });
    global.jderobot = jderobot;
}
(typeof (global) === "undefined" ? window : global, typeof (require) === "undefined" ? undefined : require));
